- name: install apache
  apt:
    name: apache2=2.4.*
    state: present
  notify:
    - restart apache2
- name: enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify:
    - restart apache2
- name: copy apach2 conf file to remote
  copy:
    src: templates/apache2.conf
    dest: /etc/apache2
    force: yes
    backup: yes
