- name: ufw set policy
  ufw:
    policy: deny
    state: enabled
- name: allow service ports
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - "80"
    - "443"
    - "22"
