- name: install php
  apt:
    name: php
    state: latest
- name: copy php.ini file to remote
  copy:
    src: templates/php.ini
    dest: /etc/php/7.0/fpm
    force: yes
    backup: yes
- name: copy php-fpm.conf file to remote
  copy:
    src: templates/php-fpm.conf
    dest: /etc/php/7.0/fpm
    force: yes
    backup: yes
- name: install php7.0-mysql
  apt:
    name: php7.0-mysql
    state: present
